services:
  bridge:
    image: ghcr.io/scorescrape/bridge:latest
    container_name: scorescrape-bridge
    environment:
      - BRIDGE_ID=<Your Bridge ID>
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  # change left side to your serial port
    group_add:
      - dialout
    restart: unless-stopped
