services:
  bridge:
    image: ghcr.io/scorescrape/bridge:latest
    container_name: scorescrape-bridge
    environment:
      # Replace with your Bridge ID
      - BRIDGE_ID=YOUR_BRIDGE_ID_HERE
    devices:
      # Change to the serial port you want to use
      # Format is local_device:container_device
      - /dev/ttyUSB0:/dev/ttyUSB0
    group_add:
      - dialout
    restart: unless-stopped